name: 💡 Idé / ønske
description: Foreslå en forbedring til Stormbreaker
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Hvad kunne gøre Stormbreaker bedre?
      placeholder: "Det ville hjælpe mig hvis Stormbreaker kunne …"
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Hvorfor? Hvad prøver du at opnå?
    validations:
      required: false
